import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import type { GlobalLeaderboardEntry, Question, SubmittedQuestion, Theme } from './types';

dotenv.config();
let pool: mysql.Pool | null = null;
const slugify = (v: string) => v.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'general';
const parseInventory = (raw: unknown) => { try { const p = typeof raw === 'string' ? JSON.parse(raw) : raw; return Array.isArray(p) ? p : []; } catch { return []; } };
const parseOptions = (raw: unknown) => { try { const p = typeof raw === 'string' ? JSON.parse(raw) : raw; return Array.isArray(p) ? p : []; } catch { return []; } };
function mapProfile(r: any): GlobalLeaderboardEntry { return { username: r.username, avatar: r.avatar || undefined, score: +r.score || 0, games_played: +r.games_played || 0, date: +r.date || Date.now(), coins: +r.coins || 0, brainCoins: +r.brainCoins || 0, is_sub: !!r.is_sub, badges: r.badges ? String(r.badges).split(',').filter(Boolean) : [], inventory: parseInventory(r.inventory), level: +r.level || 1, xp: +r.xp || 0 }; }
export async function getDb() { if (!process.env.DB_HOST || !process.env.DB_USER || !process.env.DB_NAME) throw new Error('Missing MySQL environment variables'); if (!pool) pool = mysql.createPool({ host: process.env.DB_HOST, port: Number(process.env.DB_PORT || 3306), user: process.env.DB_USER, password: process.env.DB_PASSWORD || '', database: process.env.DB_NAME, waitForConnections: true, connectionLimit: Number(process.env.DB_CONNECTION_LIMIT || 10), queueLimit: 0, connectTimeout: 10000, charset: 'utf8mb4' }); return pool; }
async function ensureUserExists(username: string, avatar?: string | null) { const db = await getDb(); await db.query(`INSERT INTO users (username, avatar, inventory) VALUES (?, ?, '[]') ON DUPLICATE KEY UPDATE avatar = COALESCE(VALUES(avatar), avatar)`, [username, avatar || null]); }
export async function initDB() { const db = await getDb(); const c = await db.getConnection(); c.release();
await db.query(`CREATE TABLE IF NOT EXISTS users (username VARCHAR(191) PRIMARY KEY, avatar VARCHAR(512) NULL, score INT NOT NULL DEFAULT 0, games_played INT NOT NULL DEFAULT 0, last_played DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, coins INT NOT NULL DEFAULT 0, brainCoins INT NOT NULL DEFAULT 0, level INT NOT NULL DEFAULT 1, xp INT NOT NULL DEFAULT 0, hp INT NOT NULL DEFAULT 100, maxHp INT NOT NULL DEFAULT 100, is_sub TINYINT(1) NOT NULL DEFAULT 0, inventory JSON NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
await db.query(`CREATE TABLE IF NOT EXISTS categories (id VARCHAR(100) PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
await db.query(`CREATE TABLE IF NOT EXISTS questions (id INT AUTO_INCREMENT PRIMARY KEY, category_id VARCHAR(100) NOT NULL, text TEXT NOT NULL, options JSON NOT NULL, correctOptionIndex INT NOT NULL, timeLimit INT NOT NULL DEFAULT 15, is_custom TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_questions_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
await db.query(`CREATE TABLE IF NOT EXISTS badges (id VARCHAR(100) PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, icon VARCHAR(255)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
await db.query(`CREATE TABLE IF NOT EXISTS user_badges (username VARCHAR(191) NOT NULL, badge_id VARCHAR(100) NOT NULL, level INT NOT NULL DEFAULT 1, xp INT NOT NULL DEFAULT 0, earned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (username, badge_id), CONSTRAINT fk_user_badges_user FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE, CONSTRAINT fk_user_badges_badge FOREIGN KEY (badge_id) REFERENCES badges(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
await db.query(`CREATE TABLE IF NOT EXISTS submit_questions (id INT AUTO_INCREMENT PRIMARY KEY, category_id VARCHAR(100) NOT NULL, text TEXT NOT NULL, options JSON NOT NULL, correctOptionIndex INT NOT NULL, author VARCHAR(191) NOT NULL, status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_submit_questions_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
await db.query(`CREATE TABLE IF NOT EXISTS shop_items (id VARCHAR(100) PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE, description TEXT, price INT NOT NULL, icon VARCHAR(255), type ENUM('attack','defense','bonus') NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
await db.query(`CREATE TABLE IF NOT EXISTS auction_items (id INT AUTO_INCREMENT PRIMARY KEY, seller VARCHAR(191) NOT NULL, item_id VARCHAR(100) NOT NULL, price INT NOT NULL, currency ENUM('coins','brainCoins') DEFAULT 'coins', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_auction_items_user FOREIGN KEY (seller) REFERENCES users(username) ON DELETE CASCADE, CONSTRAINT fk_auction_items_item FOREIGN KEY (item_id) REFERENCES shop_items(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
await seedData(); }
async function seedData(){ const db=await getDb(); for (const x of [{id:'culture-generale',name:'Culture Générale'}]) await db.query('INSERT IGNORE INTO categories (id, name) VALUES (?, ?)', [x.id,x.name]); for (const x of [{id:'first-game',name:'Première Partie',description:'A joué sa première partie',icon:'Award'},{id:'veteran',name:'Vétéran',description:'A joué 10 parties',icon:'Shield'},{id:'expert',name:'Expert',description:'A joué 50 parties',icon:'Zap'},{id:'champion',name:'Champion',description:'A gagné une partie',icon:'Star'}]) await db.query('INSERT IGNORE INTO badges (id,name,description,icon) VALUES (?,?,?,?)',[x.id,x.name,x.description,x.icon]); for (const x of [{id:'fumigene',name:'Fumigène',description:"Floute l'écran des adversaires pendant 5s",price:50,icon:'EyeOff',type:'attack'},{id:'seisme',name:'Séisme',description:"Fait trembler l'écran des adversaires",price:75,icon:'Zap',type:'attack'},{id:'inversion',name:'Inversion',description:"Met l'écran des adversaires à l'envers",price:100,icon:'RefreshCcw',type:'attack'},{id:'bouclier',name:'Bouclier',description:'Protège contre la prochaine attaque',price:50,icon:'Shield',type:'defense'}]) await db.query('INSERT IGNORE INTO shop_items (id,name,description,price,icon,type) VALUES (?,?,?,?,?,?)',[x.id,x.name,x.description,x.price,x.icon,x.type]); const t = await getThemesWithQuestions(); if (!t['culture-generale']?.questions?.length) await addQuestion({id:'q1',text:'Quelle est la capitale de la France ?',options:['Londres','Paris','Berlin','Madrid'],correctOptionIndex:1,timeLimit:15}, 'culture-generale', false); }
export async function getShopItems(): Promise<any[]> { const db=await getDb(); const [rows]=await db.query('SELECT * FROM shop_items ORDER BY price ASC, name ASC'); return rows as any[]; }
export async function getThemesWithQuestions(): Promise<Record<string, Theme>> { const db=await getDb(); const [trs]=await db.query('SELECT * FROM categories ORDER BY name ASC'); const [qrs]=await db.query('SELECT * FROM questions ORDER BY created_at ASC'); const themes: Record<string, Theme> = {}; for (const c of trs as any[]) themes[c.id]={id:c.id,name:c.name,questions:[]}; for (const q of qrs as any[]) if (themes[q.category_id]) themes[q.category_id].questions.push({id:q.id,text:q.text,options:parseOptions(q.options),correctOptionIndex:+q.correctOptionIndex,timeLimit:+q.timeLimit||15}); return themes; }
export async function addTheme(idOrName: string, displayName?: string): Promise<string | null> { const db=await getDb(); const id=slugify(idOrName); const name=displayName || idOrName; await db.query('INSERT IGNORE INTO categories (id, name) VALUES (?, ?)', [id,name]); return id; }
export async function addQuestion(q: Question, categoryId: string | number, isCustom=true) { const db=await getDb(); await db.query('INSERT INTO questions (category_id, text, options, correctOptionIndex, timeLimit, is_custom) VALUES (?, ?, ?, ?, ?, ?)', [String(categoryId), q.text, JSON.stringify(q.options), q.correctOptionIndex, q.timeLimit || 15, isCustom ? 1 : 0]); }
export async function getLeaderboard(): Promise<GlobalLeaderboardEntry[]> { const db=await getDb(); const [rows]=await db.query(`SELECT u.username,u.avatar,u.score,u.games_played,UNIX_TIMESTAMP(u.last_played)*1000 AS date,u.coins,u.brainCoins,u.level,u.xp,u.is_sub,u.inventory,GROUP_CONCAT(ub.badge_id ORDER BY ub.badge_id SEPARATOR ',') AS badges FROM users u LEFT JOIN user_badges ub ON ub.username=u.username GROUP BY u.username ORDER BY u.score DESC, u.games_played DESC, u.username ASC LIMIT 50`); return (rows as any[]).map(mapProfile); }
export async function getUserProfile(username:string): Promise<GlobalLeaderboardEntry|null> { await ensureUserExists(username); const db=await getDb(); const [rows]=await db.query(`SELECT u.username,u.avatar,u.score,u.games_played,UNIX_TIMESTAMP(u.last_played)*1000 AS date,u.coins,u.brainCoins,u.level,u.xp,u.is_sub,u.inventory,GROUP_CONCAT(ub.badge_id ORDER BY ub.badge_id SEPARATOR ',') AS badges FROM users u LEFT JOIN user_badges ub ON ub.username=u.username WHERE u.username=? GROUP BY u.username`, [username]); const row=(rows as any[])[0]; return row ? mapProfile(row) : null; }
export async function batchUpdateUserProfiles(updates:{username:string,avatar:string|undefined,score:number,coinsEarned:number,newBadges:(string|number)[]}[]){ if(!updates.length)return; const db=await getDb(); const conn=await db.getConnection(); try{ await conn.beginTransaction(); for(const u of updates){ const xp=Math.max(0,u.score)*10; await conn.query(`INSERT INTO users (username, avatar, score, games_played, last_played, coins, xp, level, inventory) VALUES (?, ?, ?, 1, CURRENT_TIMESTAMP, ?, ?, 1, '[]') ON DUPLICATE KEY UPDATE avatar=COALESCE(VALUES(avatar),avatar), score=GREATEST(score,VALUES(score)), games_played=games_played+1, last_played=CURRENT_TIMESTAMP, coins=coins+VALUES(coins), xp=xp+VALUES(xp), level=FLOOR((xp+VALUES(xp))/1000)+1`, [u.username,u.avatar||null,u.score,u.coinsEarned,xp]); for(const b of u.newBadges) await conn.query('INSERT IGNORE INTO user_badges (username, badge_id) VALUES (?, ?)', [u.username, String(b)]); } await conn.commit(); } catch(e){ await conn.rollback(); throw e; } finally{ conn.release(); } }
export async function buyItem(username:string,itemId:string|number,cost:number){ const p=await getUserProfile(username); if(!p||p.coins<cost)return false; const db=await getDb(); await db.query('UPDATE users SET coins = coins - ?, inventory = ? WHERE username = ?', [cost, JSON.stringify([...p.inventory, itemId]), username]); return true; }
export async function useItem(username:string,itemId:string|number){ const p=await getUserProfile(username); if(!p)return false; const inv=[...p.inventory]; const i=inv.findIndex(x=>x===itemId); if(i===-1)return false; inv.splice(i,1); const db=await getDb(); await db.query('UPDATE users SET inventory = ? WHERE username = ?', [JSON.stringify(inv), username]); return true; }
export async function toggleSubStatus(username:string){ const p=await getUserProfile(username); if(!p)return false; const db=await getDb(); const next=p.is_sub?0:1; await db.query('UPDATE users SET is_sub = ? WHERE username = ?', [next, username]); return !!next; }
export async function getPendingQuestions(): Promise<SubmittedQuestion[]> { const db=await getDb(); const [rows]=await db.query("SELECT * FROM submit_questions WHERE status='pending' ORDER BY created_at DESC"); return (rows as any[]).map(r=>({id:r.id,text:r.text,options:parseOptions(r.options),correctOptionIndex:+r.correctOptionIndex,author:r.author,theme:r.category_id,status:r.status})); }
export async function addSubmittedQuestion(q:SubmittedQuestion){ const db=await getDb(); await db.query('INSERT INTO submit_questions (category_id, text, options, correctOptionIndex, author, status) VALUES (?, ?, ?, ?, ?, ?)', [slugify(q.theme), q.text, JSON.stringify(q.options), q.correctOptionIndex, q.author, q.status]); }
export async function updateSubmittedQuestionStatus(id:string|number,status:'approved'|'rejected'){ const db=await getDb(); await db.query('UPDATE submit_questions SET status = ? WHERE id = ?', [status,id]); }
export async function getAllBadges(){ const db=await getDb(); const [badges]=await db.query('SELECT * FROM badges ORDER BY name ASC'); const [users]=await db.query('SELECT COUNT(*) AS count FROM users'); const total=Number((users as any[])[0]?.count||1); for(const b of badges as any[]){ const [c]=await db.query('SELECT COUNT(*) AS count FROM user_badges WHERE badge_id = ?', [b.id]); b.rarity=Math.round((Number((c as any[])[0]?.count||0)/total)*100); } return badges as any[]; }
export async function getAuctionItems(): Promise<any[]> { const db=await getDb(); const [rows]=await db.query(`SELECT ai.id, ai.seller, ai.item_id AS itemId, ai.price, ai.currency, UNIX_TIMESTAMP(ai.created_at)*1000 AS createdAt, si.name, si.description, si.icon, si.type FROM auction_items ai JOIN shop_items si ON si.id=ai.item_id ORDER BY ai.created_at DESC`); return rows as any[]; }
export async function awardBadgeXp(username:string,badgeId:string|number,xp:number){ const db=await getDb(); const bid=String(badgeId); const [rows]=await db.query('SELECT xp FROM user_badges WHERE username = ? AND badge_id = ?', [username,bid]); const current=Number((rows as any[])[0]?.xp||0); const next=current+xp; const level=Math.floor(next/100)+1; await db.query(`INSERT INTO user_badges (username,badge_id,level,xp) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE xp=VALUES(xp), level=VALUES(level)`, [username,bid,level,next]); }
export async function updateUserProfile(username:string,updates:Partial<any>){ const keys=Object.keys(updates).filter(k=>updates[k]!==undefined); if(!keys.length)return; const db=await getDb(); await db.query(`UPDATE users SET ${keys.map(k=>`${k} = ?`).join(', ')} WHERE username = ?`, [...keys.map(k=>updates[k]), username]); }
export async function openLootBox(username:string,boxType:'standard'|'premium'): Promise<{success:boolean,item?:any,message?:string}>{ const p=await getUserProfile(username); if(!p)return{success:false,message:'Profil introuvable'}; const currency=boxType==='standard'?'coins':'brainCoins'; const cost=boxType==='standard'?500:5; if((p as any)[currency]<cost)return{success:false,message:'Fonds insuffisants'}; const items=await getShopItems(); if(!items.length)return{success:false,message:'Boutique vide'}; const reward=items[Math.floor(Math.random()*items.length)]; const db=await getDb(); await db.query(`UPDATE users SET ${currency} = ${currency} - ?, inventory = ? WHERE username = ?`, [cost, JSON.stringify([...p.inventory,reward.id]), username]); return {success:true,item:reward}; }
export async function listItemForAuction(username:string,itemId:string|number,price:number,currency:'coins'|'brainCoins'){ const p=await getUserProfile(username); if(!p)return false; const inv=[...p.inventory]; const i=inv.findIndex(x=>x===itemId); if(i===-1)return false; inv.splice(i,1); const db=await getDb(); const conn=await db.getConnection(); try{ await conn.beginTransaction(); await conn.query('UPDATE users SET inventory = ? WHERE username = ?', [JSON.stringify(inv), username]); await conn.query('INSERT INTO auction_items (seller, item_id, price, currency) VALUES (?, ?, ?, ?)', [username, String(itemId), price, currency]); await conn.commit(); return true; } catch(e){ await conn.rollback(); throw e; } finally { conn.release(); } }
export async function addBrainCoins(username:string,amount:number){ await ensureUserExists(username); const db=await getDb(); await db.query('UPDATE users SET brainCoins = brainCoins + ? WHERE username = ?', [amount, username]); return true; }
